name: Deploy to GitHub Pages

# main ブランチ の push 時にこのワークフローを実行する
on:
 push:
   branches:
     - main

jobs:
  build-deploy:
    # ubuntu OS を仮想マシン上に用意する
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Node.js環境のセットアップを行う
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
        node-version: "19.7.0"
        cache: yarn

     # パッケージをインストールする
     - name: Install dependencies
       run: yarn --frozen-lockfile

     # ビルドする
     - name: Build
       run: yarn build

     # GitHub Pages にデプロイする
     - name: Deploy
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: out